const { db } = require('./src/config/db');
const bcrypt = require('bcryptjs');

const employees = [
  {
    name: "Aarav Sharma",
    phone: "+91 98110 11223",
    email: "aarav.s@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Block C, Vasant Kunj, New Delhi",
    emergency_contact: "Rahul Sharma: +91 98110 99887",
    skills: "Welding, Fabrication",
    job_role: "Senior Welder",
    joined_date: "2025-01-10",
    father_name: "Ravi Sharma",
    mother_name: "Sunita Sharma",
    dob: "1990-04-12",
    gender: "Male",
    blood_group: "O+",
    pan_number: "ABCDE1234F",
    aadhaar_number: "1122 3344 5566",
    uan_number: "100223344550",
    bank_name: "HDFC Bank",
    bank_branch: "Vasant Kunj",
    bank_account: "12345678901",
    bank_ifsc: "HDFC0001234",
    bank_holder_name: "Aarav Sharma",
    qualification: "ITI Welding",
    experience_years: 8,
    status: "active"
  },
  {
    name: "Priya Patel",
    phone: "+91 99220 33445",
    email: "priya.p@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Navrangpura, Ahmedabad",
    emergency_contact: "Amit Patel: +91 99220 55667",
    skills: "Project Management, QA",
    job_role: "Quality Inspector",
    joined_date: "2024-11-05",
    father_name: "Kamlesh Patel",
    mother_name: "Bhavna Patel",
    dob: "1992-08-22",
    gender: "Female",
    blood_group: "A+",
    pan_number: "PQRTS5678G",
    aadhaar_number: "2233 4455 6677",
    uan_number: "100334455660",
    bank_name: "SBI",
    bank_branch: "Navrangpura",
    bank_account: "23456789012",
    bank_ifsc: "SBIN0002345",
    bank_holder_name: "Priya Patel",
    qualification: "B.Tech Civil",
    experience_years: 5,
    status: "active"
  },
  {
    name: "Rohan Gupta",
    phone: "+91 98330 44556",
    email: "rohan.g@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Koramangala, Bangalore",
    emergency_contact: "Sunil Gupta: +91 98330 66778",
    skills: "Heavy Machinery Operation",
    job_role: "Crane Operator",
    joined_date: "2023-03-15",
    father_name: "Rakesh Gupta",
    mother_name: "Meena Gupta",
    dob: "1988-11-30",
    gender: "Male",
    blood_group: "B+",
    pan_number: "LMNO9012H",
    aadhaar_number: "3344 5566 7788",
    uan_number: "100445566770",
    bank_name: "Axis Bank",
    bank_branch: "Koramangala",
    bank_account: "34567890123",
    bank_ifsc: "UTIB0003456",
    bank_holder_name: "Rohan Gupta",
    qualification: "High School, Heavy License",
    experience_years: 10,
    status: "active"
  },
  {
    name: "Neha Singh",
    phone: "+91 98440 55667",
    email: "neha.s@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Gomti Nagar, Lucknow",
    emergency_contact: "Rajput Singh: +91 98440 77889",
    skills: "Accounting, Admin",
    job_role: "Site Admin",
    joined_date: "2025-02-01",
    father_name: "Vikas Singh",
    mother_name: "Rita Singh",
    dob: "1995-02-14",
    gender: "Female",
    blood_group: "AB+",
    pan_number: "XYZA3456I",
    aadhaar_number: "4455 6677 8899",
    uan_number: "100556677880",
    bank_name: "PNB",
    bank_branch: "Gomti Nagar",
    bank_account: "45678901234",
    bank_ifsc: "PUNB0004567",
    bank_holder_name: "Neha Singh",
    qualification: "B.Com",
    experience_years: 3,
    status: "active"
  },
  {
    name: "Vikram Das",
    phone: "+91 98550 66778",
    email: "vikram.d@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Salt Lake City, Kolkata",
    emergency_contact: "Arun Das: +91 98550 88990",
    skills: "Electrical Wiring, Setup",
    job_role: "Electrician",
    joined_date: "2022-09-10",
    father_name: "Sanjay Das",
    mother_name: "Anita Das",
    dob: "1985-07-25",
    gender: "Male",
    blood_group: "O-",
    pan_number: "BCDE7890J",
    aadhaar_number: "5566 7788 9900",
    uan_number: "100667788990",
    bank_name: "Bank of Baroda",
    bank_branch: "Salt Lake",
    bank_account: "56789012345",
    bank_ifsc: "BARB0SALKOL",
    bank_holder_name: "Vikram Das",
    qualification: "ITI Electrical",
    experience_years: 15,
    status: "active"
  },
  {
    name: "Meera Reddy",
    phone: "+91 98660 77889",
    email: "meera.r@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Jubilee Hills, Hyderabad",
    emergency_contact: "Kiran Reddy: +91 98660 99001",
    skills: "Architecture, CAD",
    job_role: "Site Architect",
    joined_date: "2024-01-20",
    father_name: "Prakash Reddy",
    mother_name: "Laxmi Reddy",
    dob: "1991-03-05",
    gender: "Female",
    blood_group: "B-",
    pan_number: "CDEF1234K",
    aadhaar_number: "6677 8899 0011",
    uan_number: "100778899000",
    bank_name: "Kotak Mahindra",
    bank_branch: "Jubilee Hills",
    bank_account: "67890123456",
    bank_ifsc: "KKBK0006789",
    bank_holder_name: "Meera Reddy",
    qualification: "B.Arch",
    experience_years: 7,
    status: "active"
  },
  {
    name: "Suresh Kumar",
    phone: "+91 98770 88990",
    email: "suresh.k@trinetra.io",
    password: "password123",
    role: "worker",
    address: "T Nagar, Chennai",
    emergency_contact: "Ramesh Kumar: +91 98770 00112",
    skills: "Plumbing, Pipe Fitting",
    job_role: "Master Plumber",
    joined_date: "2021-12-01",
    father_name: "Murugan Kumar",
    mother_name: "Kavitha Kumar",
    dob: "1982-10-18",
    gender: "Male",
    blood_group: "A-",
    pan_number: "DEFG5678L",
    aadhaar_number: "7788 9900 1122",
    uan_number: "100889900110",
    bank_name: "Indian Bank",
    bank_branch: "T Nagar",
    bank_account: "78901234567",
    bank_ifsc: "IDIB0007890",
    bank_holder_name: "Suresh Kumar",
    qualification: "ITI Plumbing",
    experience_years: 20,
    status: "active"
  },
  {
    name: "Ananya Desai",
    phone: "+91 98880 99001",
    email: "ananya.d@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Deccan Gymkhana, Pune",
    emergency_contact: "Rahul Desai: +91 98880 11223",
    skills: "HR, Recruitment",
    job_role: "HR Coordinator",
    joined_date: "2023-08-14",
    father_name: "Vinod Desai",
    mother_name: "Smita Desai",
    dob: "1994-05-27",
    gender: "Female",
    blood_group: "O+",
    pan_number: "EFGH9012M",
    aadhaar_number: "8899 0011 2233",
    uan_number: "100990011220",
    bank_name: "ICICI Bank",
    bank_branch: "Deccan",
    bank_account: "89012345678",
    bank_ifsc: "ICIC0008901",
    bank_holder_name: "Ananya Desai",
    qualification: "MBA HR",
    experience_years: 4,
    status: "active"
  },
  {
    name: "Karan Malhotra",
    phone: "+91 98990 00112",
    email: "karan.m@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Sector 17, Chandigarh",
    emergency_contact: "Rajeev Malhotra: +91 98990 22334",
    skills: "Safety Compliance, First Aid",
    job_role: "Safety Officer",
    joined_date: "2024-04-10",
    father_name: "Anil Malhotra",
    mother_name: "Pooja Malhotra",
    dob: "1989-12-09",
    gender: "Male",
    blood_group: "B+",
    pan_number: "FGHI3456N",
    aadhaar_number: "9900 1122 3344",
    uan_number: "100001122330",
    bank_name: "HDFC Bank",
    bank_branch: "Sector 17",
    bank_account: "90123456789",
    bank_ifsc: "HDFC0009012",
    bank_holder_name: "Karan Malhotra",
    qualification: "Diploma in Industrial Safety",
    experience_years: 9,
    status: "active"
  },
  {
    name: "Divya Nair",
    phone: "+91 99000 11223",
    email: "divya.n@trinetra.io",
    password: "password123",
    role: "worker",
    address: "Marine Drive, Kochi",
    emergency_contact: "Suresh Nair: +91 99000 33445",
    skills: "Data Entry, Material Tracking",
    job_role: "Inventory Clerk",
    joined_date: "2025-03-01",
    father_name: "Mohan Nair",
    mother_name: "Geetha Nair",
    dob: "1996-01-20",
    gender: "Female",
    blood_group: "A+",
    pan_number: "GHIJ7890O",
    aadhaar_number: "0011 2233 4455",
    uan_number: "100112233440",
    bank_name: "Federal Bank",
    bank_branch: "Marine Drive",
    bank_account: "01234567890",
    bank_ifsc: "FDRL0000123",
    bank_holder_name: "Divya Nair",
    qualification: "B.A. Economics",
    experience_years: 2,
    status: "active"
  }
];

async function seedEmployees() {
  try {
    const hashedPassword = await bcrypt.hash("password123", 10);
    
    db.transaction(() => {
      const userStmt = db.prepare('INSERT INTO users (name, phone, email, password, role, company_id) VALUES (?, ?, ?, ?, ?, ?)');
      const workerStmt = db.prepare(`
        INSERT INTO workers (
          user_id, address, emergency_contact, skills, job_role, joined_date,
          father_name, mother_name, dob, gender, blood_group,
          pan_number, aadhaar_number, uan_number,
          bank_name, bank_branch, bank_account, bank_ifsc, bank_holder_name,
          qualification, experience_years, status
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);
      const docStmt = db.prepare('INSERT INTO documents (worker_id, type, file_url) VALUES (?, ?, ?)');
      const logStmt = db.prepare('INSERT INTO audit_logs (user_id, action, target_type, target_id) VALUES (?, ?, ?, ?)');

      for (const emp of employees) {
        const userInfo = userStmt.run(emp.name, emp.phone, emp.email, hashedPassword, emp.role, 1);
        const workerId = userInfo.lastInsertRowid;
        
        workerStmt.run(
          workerId, emp.address, emp.emergency_contact, emp.skills, emp.job_role, emp.joined_date,
          emp.father_name, emp.mother_name, emp.dob, emp.gender, emp.blood_group,
          emp.pan_number, emp.aadhaar_number, emp.uan_number,
          emp.bank_name, emp.bank_branch, emp.bank_account, emp.bank_ifsc, emp.bank_holder_name,
          emp.qualification, emp.experience_years, emp.status
        );

        docStmt.run(workerId, 'aadhaar', '/uploads/mock_aadhaar.pdf');
        docStmt.run(workerId, 'pan', '/uploads/mock_pan.jpg');
        
        logStmt.run(1, 'ADD_WORKER_TEST', 'worker', workerId);
      }
    })();
    console.log("Successfully seeded 10 employees.");
  } catch (err) {
    console.error("Failed to seed employees:", err);
  }
}

seedEmployees();
